-- Demo data: the integrator fills this in after entities and contracts are agreed.
-- Use fixed identifiers and UPSERT so a rerun does not create duplicates.
-- One database for the whole team: run/reset only in an agreed window.
-- No TRUNCATE, no deleting other people's data and no automatic runs in CI/preview.
