/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin sources; analyst permitted upload scopes. */
    get: operations["source_list"];
    put?: never;
    /** Admin: register the allowlisted dataset. */
    post: operations["source_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/connector": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin: copy a registered batch to private quarantine. */
    post: operations["import_connector"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin or assigned analyst: stage CSV or text PDF in private storage. */
    post: operations["import_upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticated: role-filtered approved excerpt search. */
    post: operations["excerpt_search"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/excerpts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Authenticated: read one approved excerpt after fresh checks. */
    get: operations["excerpt_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticated: create a pending controlled chat run. */
    post: operations["chat_start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticated: create a public-only PDF summary run. */
    post: operations["export_start"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{id}/execute": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Owner or admin: acquire lease and synchronously execute pending work. */
    post: operations["run_execute"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Owner or admin: progress or completed result. */
    get: operations["run_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/runs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Owner or admin: request cancellation before further work. */
    post: operations["run_cancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/exports/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Owner or admin: revalidate audience and stream newly generated PDF. */
    get: operations["export_download"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin only: pending review candidates, page limit 50. */
    get: operations["review_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reviews/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin only: candidate extract for inspection. */
    get: operations["review_read"];
    /** Admin: edit and rescan a versioned candidate before approval. */
    put: operations["review_resolve"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/policy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin only: current validated central policy. */
    get: operations["policy_read"];
    /** Admin: compare-and-swap full policy. */
    put: operations["policy_update"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin active feed snapshot. */
    get: operations["feed_read"];
    put?: never;
    /** Admin or scoped feed publisher: validate and activate feed snapshot. */
    post: operations["feed_import"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Actor own sanitized traces; admin organisation traces. Limit 100. */
    get: operations["audit_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audit/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Actor own sanitized trace detail; admin same organisation. */
    get: operations["audit_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Own imports; admin organisation imports; no raw text. */
    get: operations["import_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Own metrics; admin may select organisation scope. */
    get: operations["metrics_read"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audit/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download sanitized audit CSV for authorised scope. */
    get: operations["audit_export"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Decision: "ALLOW" | "REDACT" | "REVIEW" | "BLOCK";
    Usage: {
      generation_input_tokens: number | null;
      generation_output_tokens: number | null;
      generation_ms: number | null;
      semantic_input_tokens: number | null;
      semantic_ms: number;
      reserved_generation_tokens: number;
      unresolved_reservation: boolean;
      comparison_micro_usd: number | null;
      comparison_rate_version: string;
    };
    Citation: {
      /** Format: uuid */
      excerpt_id: string;
      excerpt_version: number;
      source_label: string;
      /** Format: date */
      source_date: string;
      period: string;
      locator: string;
    };
    Excerpt: {
      /** Format: uuid */
      id: string;
      version: number;
      text: string;
      /** @enum {string} */
      classification: "public" | "internal" | "restricted";
      citation: components["schemas"]["Citation"];
    };
    Finding: {
      code: string;
      category: string;
      /** @enum {string} */
      severity: "info" | "review" | "block";
      stage: string;
      locator: string | null;
    };
    Assessment: {
      /** @enum {string} */
      status: "complete" | "not_required" | "unavailable" | "incomplete";
      scores: {
        instruction_manipulation: number | null;
        sensitive_exposure: number | null;
        resource_abuse: number | null;
      };
      checkpoint_revision: string | null;
      windows_planned: number;
      windows_completed: number;
      coverage_complete: boolean;
      text_sha256: string | null;
      coverage_ranges: {
        start_char: number;
        end_char: number;
        input_tokens: number;
      }[];
      chat_checks?: components["schemas"]["ChatCheck"][];
    };
    Run: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      kind: "import" | "chat" | "export";
      /** @enum {string} */
      state:
        | "pending"
        | "running"
        | "completed"
        | "review"
        | "blocked"
        | "failed"
        | "cancel_requested"
        | "cancelled"
        | "incomplete";
      stage: string;
    };
    Review: {
      /** Format: uuid */
      id: string;
      version: number;
      candidate_text: string;
      /** @enum {string} */
      classification: "public" | "internal" | "restricted";
      /** @enum {string} */
      status: "pending" | "approved" | "rejected" | "expired";
      /** Format: uuid */
      document_id: string;
    };
    Response: {
      /** Format: uuid */
      trace_id: string;
      decision: components["schemas"]["Decision"] | null;
      reasons: string[];
      policy_version: number | null;
      feed_version: number | null;
      semantic: components["schemas"]["Assessment"];
      usage: components["schemas"]["Usage"];
      timings: {
        total_ms: number;
        deterministic_ms: number;
        semantic_ms: number;
        provider_ms: number;
        persistence_ms: number;
      };
      data:
        | null
        | components["schemas"]["Run"]
        | {
            items: components["schemas"]["Excerpt"][];
          }
        | components["schemas"]["Excerpt"]
        | {
            /** @constant */
            selection_required: true;
            sources: {
              /** Format: uuid */
              id: string;
              label: string;
              /** Format: date-time */
              created_at: string;
            }[];
          }
        | {
            answer: string;
            citations: components["schemas"]["Citation"][];
          }
        | components["schemas"]["Review"]
        | {
            download_path: string;
            /** Format: date-time */
            expires_at: string;
          }
        | {
            version: number;
          }
        | {
            items: components["schemas"]["Review"][];
          }
        | {
            items: components["schemas"]["AuditProjection"][];
          }
        | {
            /** Format: uuid */
            source_id: string;
          }
        | {
            policy: components["schemas"]["policy.schema"];
          }
        | {
            items: components["schemas"]["SourceSummary"][];
          }
        | {
            items: components["schemas"]["ImportSummary"][];
          }
        | components["schemas"]["Metrics"]
        | {
            feed: components["schemas"]["threat-feed.schema"];
          }
        | {
            /** Format: uuid */
            review_id: string;
          };
      error: null | {
        /** @enum {string} */
        code:
          | "INVALID_INPUT"
          | "UNAUTHENTICATED"
          | "ACCESS_DENIED"
          | "NOT_FOUND"
          | "CONFLICT"
          | "RATE_LIMITED"
          | "BUDGET_EXHAUSTED"
          | "POLICY_UNAVAILABLE"
          | "SEMANTIC_UNAVAILABLE"
          | "MODEL_UNAVAILABLE"
          | "AUDIT_UNAVAILABLE"
          | "STATE_UNAVAILABLE"
          | "UNSUPPORTED_FILE"
          | "CANCELLED"
          | "INCOMPLETE";
        message: string;
        retryable: boolean;
      };
    };
    AuditProjection: {
      /** Format: uuid */
      trace_id: string;
      /** Format: uuid */
      actor_id: string;
      operation: string;
      /** Format: date-time */
      created_at: string;
      decision: components["schemas"]["Decision"] | null;
      reasons: string[];
      state: string;
      policy_version: number;
      feed_version: number;
      usage: components["schemas"]["Usage"];
      events?: {
        stage: string;
        event_type: string;
        /** Format: date-time */
        created_at: string;
        policy_version: number;
        feed_version: number;
        findings: components["schemas"]["Finding"][];
        semantic: components["schemas"]["Assessment"];
        usage: components["schemas"]["Usage"];
      }[];
    };
    SearchRequest: {
      query: string;
      /** Format: uuid */
      deal_id?: string;
      /** Format: uuid */
      source_id?: string;
    };
    ChatRequest: {
      message: string;
      /** Format: uuid */
      deal_id?: string;
      /** Format: uuid */
      source_id?: string;
    };
    ExportRequest: {
      topic: string;
      /** Format: uuid */
      deal_id?: string;
    };
    ReviewRequest: {
      expected_version: number;
      /** @enum {string} */
      action: "approve" | "reject";
      candidate_text: string;
      /** @enum {string} */
      classification: "public" | "internal" | "restricted";
      reason: string;
      evidence_excerpt_ids: string[];
    };
    PolicyUpdate: {
      expected_version: number;
      policy: components["schemas"]["policy.schema"];
    };
    FeedUpdate: {
      expected_version: number;
      feed: components["schemas"]["threat-feed.schema"];
    };
    SourceRequest: {
      label: string;
      /** @constant */
      dataset: "demo_dataset_v1";
      /** @enum {string} */
      classification: "public" | "internal" | "restricted";
      /** Format: uuid */
      deal_id?: string;
      /**
       * @default unverified
       * @enum {string}
       */
      audience_evidence: "verified" | "unverified";
    };
    ConnectorImport: {
      /** Format: uuid */
      source_id: string;
      /** Format: uuid */
      batch_id: string;
    };
    SourceSummary: {
      /** Format: uuid */
      id: string;
      label: string;
      /** @enum {unknown} */
      classification: "public" | "internal" | "restricted";
      /** @enum {unknown} */
      kind: "dataset" | "upload";
    };
    ImportSummary: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      run_id: string;
      /** @enum {unknown} */
      status: "quarantined" | "processing" | "approved" | "partial" | "review" | "blocked" | "failed";
      /** @enum {unknown} */
      classification: "public" | "internal" | "restricted";
    };
    Metrics: {
      /** @enum {unknown} */
      scope: "own" | "organisation";
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
      root_requests: number;
      blocked_attempts: number;
      stopped_loops: number;
      review_cases: number;
      confirmed_test_failures: number | null;
      usage: components["schemas"]["Usage"];
      permitted_source_tokens_estimate: number | null;
      selected_source_tokens_estimate: number | null;
      context_reduction_percent: number | null;
      estimated_avoided_input_micro_usd: number | null;
      /** Format: uuid */
      context_trace_id: string | null;
    };
    SecurityVerdict: {
      instruction_manipulation: boolean;
      sensitive_exposure: boolean;
      resource_abuse: boolean;
      uncertain: boolean;
    };
    ChatCheck: {
      /** @enum {unknown} */
      operation: "chat_input" | "chat_output";
      laya_scores: {
        instruction_manipulation: number | null;
        sensitive_exposure: number | null;
        resource_abuse: number | null;
      };
      text_sha256: string;
      verification: null | {
        /** @constant */
        protocol: "qwen-context-v1";
        model_digest: string;
        verdict: components["schemas"]["SecurityVerdict"];
        input_tokens: number | null;
        output_tokens: number | null;
        duration_ms: number | null;
      };
    };
    /** GatewayPolicy */
    "policy.schema": {
      /** @constant */
      schema_version: 1;
      version: number;
      /** @enum {string} */
      mode: "balanced" | "strict";
      imports: {
        max_bytes: number;
        max_pdf_pages: number;
        max_csv_rows: number;
        max_text_chars: number;
        max_processing_ms: number;
        allowed_formats: ("csv" | "pdf")[];
        /** @constant */
        connector_dataset: "demo_dataset_v1";
      };
      semantic: {
        /** @constant */
        required: true;
        /** @constant */
        checkpoint: "typed-decisions";
        /** @constant */
        context_tokens: 1024;
        window_tokens: number;
        overlap_tokens: number;
        max_windows: number;
        timeout_ms: number;
        thresholds: {
          instruction_manipulation: {
            review: number;
            block: number;
          };
          sensitive_exposure: {
            review: number;
            block: number;
          };
          resource_abuse: {
            review: number;
            block: number;
          };
        };
        /**
         * @description Optional bounded Qwen verification for balanced-mode chat only; semantic protocol v2. Laya scores at or above 0.7 and deterministic denials remain withholding.
         * @constant
         */
        chat_verification?: "qwen-context-v1";
      };
      execution: {
        /** @constant */
        generation_model: "qwen3:8b";
        /** @constant */
        thinking: false;
        context_tokens: number;
        max_input_utf8_bytes: number;
        template_token_reserve: number;
        max_output_tokens: number;
        max_model_turns: number;
        max_tool_calls: number;
        max_identical_tool_calls: number;
        max_elapsed_ms: number;
        provider_timeout_ms: number;
        max_search_results: number;
        max_excerpt_chars: number;
        allowed_tools: ("search_excerpts" | "read_excerpt")[];
      };
      budgets: {
        /** @constant */
        period: "utc_day";
        actor_generation_tokens: number;
        org_generation_tokens: number;
        actor_generation_ms: number;
        org_generation_ms: number;
        actor_semantic_tokens: number;
        org_semantic_tokens: number;
        actor_commercial_micro_usd: number;
        org_commercial_micro_usd: number;
        requests_per_actor_minute: number;
        max_active_runs_per_actor: number;
        max_active_runs_per_org: number;
      };
      comparison_rate: {
        version: string;
        /** @constant */
        currency: "USD";
        input_micro_usd_per_token: number;
        output_micro_usd_per_token: number;
        /** @constant */
        label: "Illustrative commercial equivalent; not an invoice";
      };
      retention: {
        raw_days: number;
        audit_days: number;
        export_minutes: number;
        review_days: number;
      };
    };
    "threat-feed.schema": {
      /** @constant */
      schema_version: 1;
      version: number;
      source: string;
      /** Format: date-time */
      published_at: string;
      /** Format: date-time */
      expires_at: string;
      indicators: {
        id: string;
        /** @enum {string} */
        kind: "literal" | "domain";
        value: string;
        /** @enum {string} */
        category: "prompt_injection" | "exfiltration" | "unsafe_code" | "resource_abuse";
        /** @enum {string} */
        action: "REVIEW" | "BLOCK";
        description: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  source_list: {
    parameters: {
      query?: {
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  source_create: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceRequest"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  import_connector: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectorImport"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  import_upload: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
          /** @enum {string} */
          classification: "public" | "internal" | "restricted";
          /** Format: uuid */
          deal_id?: string;
          /** Format: date */
          source_date?: string;
          period?: string;
          unit?: string;
          fact_key?: string;
          /** @enum {string} */
          basis?: "actual" | "forecast" | "proposal" | "event";
        };
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  excerpt_search: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  excerpt_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  chat_start: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  export_start: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  run_execute: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  run_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  run_cancel: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  export_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Private, no-store PDF. Trace ID in X-Trace-ID. JSON failures follow Response. */
      200: {
        headers: {
          "X-Trace-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  review_list: {
    parameters: {
      query?: {
        /** @description Last ID from prior page; ordering and cursor details in data-model.md. */
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  review_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  review_resolve: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  policy_read: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  policy_update: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyUpdate"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  feed_read: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  feed_import: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedUpdate"];
      };
    };
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  audit_list: {
    parameters: {
      query?: {
        /** @description Last ID from prior page; ordering and cursor details in data-model.md. */
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  audit_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  import_list: {
    parameters: {
      query?: {
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  metrics_read: {
    parameters: {
      query?: {
        scope?: "own" | "organisation";
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Governed outcome. Inspect decision and error; HTTP success alone is not approval. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
  audit_export: {
    parameters: {
      query?: {
        scope?: "own" | "organisation";
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Safe CSV, authenticated scoped export. X-Trace-ID identifies access. */
      200: {
        headers: {
          "X-Trace-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
      /** @description See protocols.md for error semantics. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description See protocols.md for error semantics. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
    };
  };
}
