/*
 * English copy for the audit screens. Every string here is the one agreed in the state
 * matrix prepared for T08, so screens and tests quote a single source instead of drifting.
 * Honesty rules encoded in these words: unknown is not zero, a refusal is not a breach,
 * and an unavailable assessment is not a pass.
 */
export const copy = {
  page: {
    traceTitle: "Trace detail",
    traceDescription: "One audited operation: its decision, stages, assessment and measured resource use.",
    dashboardTitle: "Activity and usage",
    dashboardDescription: "Your audited operations, security decisions and measured resource use.",
  },
  label: {
    notMeasured: "Not measured",
    unknown: "Unknown",
    na: "N/A",
    actual: "Actual",
    reserved: "Reserved",
    unknownColumn: "Unknown",
    noLocator: "No locator",
    noHash: "No hash recorded",
    noRevision: "Revision not reported",
    traceId: "Trace",
    actorId: "Actor",
    state: "State",
    reasons: "Reason codes",
    policyVersion: "Policy version",
    feedVersion: "Threat feed version",
    rootRequest: "root request",
  },
  usage: {
    title: "Resource use",
    generationInput: "Generation input",
    generationOutput: "Generation output",
    generationDuration: "Generation duration",
    semanticInput: "Assessment input (Laya)",
    semanticDuration: "Assessment duration (Laya)",
    reservedTokens: "Reserved generation tokens",
    unresolved: "Unresolved reservation retained",
    reservedHint: "Retained until the reservation is reconciled. Never added to actual use.",
    unknownHint: "No value was recorded. Unknown use is not zero use.",
  },
  decision: {
    allow: "Allowed",
    redact: "Partly withheld",
    review: "Held for review",
    block: "Blocked",
    pending: "Pending",
    pendingHint: "No decision recorded yet.",
    reviewHint: "Output is withheld until an administrator decides.",
  },
  stages: {
    title: "Stages",
    description: "Each recorded step of this operation, in the order the gateway stored it.",
    findings: "Findings",
    noFindings: "No findings recorded for this stage.",
    stageUsage: "Stage resource use",
    emptyTitle: "No stages recorded",
    emptyDescription: "This trace has no stage events in the audit store.",
    rootStage: "Root operation",
    toolSubcall: "Tool subcall",
    subcallHint: "Tool subcalls belong to the root request above and are not counted again.",
    showSubcalls: "Show tool subcalls",
  },
  assessment: {
    title: "Assessment",
    complete: "Assessment complete",
    notRequired: "Assessment not required",
    unavailable: "Assessment unavailable",
    incomplete: "Assessment incomplete",
    unavailableHint: "Required assessment did not complete; the operation was withheld.",
    notRequiredHint: "Not required is not a pass; no assessment was performed for this stage.",
    incompleteHint: "The assessment did not cover the whole input, so it is not a pass.",
    scoreHint: "A score grants no permission. Policy enforcement is deterministic.",
    instruction: "Instruction manipulation",
    exposure: "Sensitive exposure",
    abuse: "Resource abuse",
    windows: "Windows assessed",
    revision: "Checkpoint revision",
    hash: "Assessed text hash",
    ranges: "Coverage ranges",
  },
  state: {
    loading: "Loading audit records…",
    incompleteTitle: "Incomplete operation.",
    incompleteBody: "Usage is retained as reserved until it is reconciled.",
    cancelledTitle: "Cancelled.",
    cancelledBody: "Cancellation does not prove the provider stopped work.",
    coverageIncomplete: "Coverage incomplete: {completed} of {planned} windows assessed.",
    eventCapTitle: "This trace has more stages than one response can return.",
    eventCapBody: "Narrow the range to inspect the remaining stages.",
    notFoundTitle: "This trace is not available.",
    notFoundBody: "Check the trace identifier, or return to your activity list.",
    deniedBody: "Organisation reporting is not available to your account.",
    unauthenticatedTitle: "Your session has ended.",
    unauthenticatedBody: "Sign in again to view audit records.",
    invalidInputBody: "Select a range inside a single UTC day.",
    rateLimitedBody: "Too many requests. Try again shortly.",
    auditUnavailableTitle: "Audit records are unavailable.",
    auditUnavailableBody: "The record for a recent operation may not exist yet.",
    stateUnavailableTitle: "Reporting state is unavailable.",
    stateUnavailableBody: "Values shown earlier may be out of date.",
    clientErrorTitle: "Something went wrong while loading this view.",
    clientErrorBody: "Try again.",
  },
  metrics: {
    controlsTitle: "Security decisions",
    resourcesTitle: "Resource use",
    estimatesTitle: "Context and illustrative cost",
    measuredUse: "Measured use",
    illustrativeCost: "Illustrative commercial equivalent",
    rootRequests: "Root requests",
    rootHint: "Root requests only; tool subcalls are not counted again.",
    blockedAttempts: "Blocked attempts",
    stoppedLoops: "Stopped loops",
    reviewCases: "Review cases",
    testFailures: "Confirmed test failures",
    testHint: "No dated test report yet.",
    scopeOwn: "Own activity",
    scopeOrganisation: "Organisation activity",
    scopeLabel: "Reporting scope",
    scopeDeniedHint: "Nothing from the organisation scope is shown, including the activity list.",
    rangeLabel: "UTC window",
    permittedCorpus: "Permitted corpus tokens",
    selectedContext: "Selected context tokens",
    contextReduction: "Context reduction",
    avoidedSpend: "Estimated avoided input spend",
    reductionSource: "Reduction source trace",
    emptyTitle: "No audit records for this UTC day.",
    emptyDescription: "Choose another day to see earlier activity.",
    estimatedBadge: "Estimated",
  },
  range: {
    label: "UTC day",
    current: "Current UTC day",
    today: "Back to the current UTC day",
    listNote: "The activity list is not filtered by day; it is the most recent records this scope can see.",
    windowMismatch: "The gateway reported a window wider than one UTC day, so it is shown as reported.",
  },
  activity: {
    title: "Recent activity",
    description: "The most recent audited operations in this scope, newest first.",
    // Not "for this UTC day": GET /audit takes no range parameter, so this list is not day-scoped.
    emptyTitle: "No audit records are visible in this scope.",
    emptyDescription: "Records appear here once an audited operation has been stored.",
    pageCap: "Showing the 100 most recent records.",
    loadOlder: "Load older records",
    loadingOlder: "Loading older records…",
    olderFailed: "Older records could not be loaded.",
    openTrace: "Open trace",
    tokens: "Settled generation tokens",
  },
  export: {
    button: "Download audit CSV",
    preparing: "Preparing CSV…",
    done: "CSV downloaded. Export trace {trace}.",
    doneNoTrace: "CSV downloaded. The gateway reported no export trace identifier.",
    overCapTitle: "This export exceeds 1000 rows.",
    failedTitle: "The export could not be prepared.",
    failedBody: "Try again, or narrow the range.",
    deniedBody: "This export is not available to your account.",
    neutralisation: "Cells are neutralised by the gateway, and the export itself is an audited access.",
  },
  disclaimer: {
    overhead: "Gateway overhead breakdown is not exposed by this endpoint.",
    blocked: "Blocked attempts are refused requests, not confirmed breaches.",
    money: "Illustrative commercial equivalent; not an invoice.",
    estimate: "Estimated from the permitted corpus using one pinned estimator.",
    noBaseline: "No source trace is recorded for this window, so the estimates are not shown.",
  },
  action: {
    retry: "Try again",
  },
} as const;

/** Fills `{name}` placeholders; used for the few strings that carry counts. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}
